services:
  personal-loan:
    image: ocr/ocr:dev
    # image: personal-loan
    container_name: personal-loan
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4003:3000"
