version: "3.7"
services:
  personal-loan:
    image: faiazhossain10/personal-loan:{TAG}
    # image: personal-loan
    container_name: personal-loan
    restart: unless-stopped
    ports:
      - "4003:3000"
